### ISSUE TITLE
RigidBodySimulation.recordTrajectory() return incorrect result.

### ISSUE THREAD

**Issue by yck011522** [computational-robotics-lab/comp-fab-a2#4]
When implementing the "evaluate" function in class "MatchTrajectoryObjective" (Task2.2)

Results from  sim.recordTrajectory() is a matrix that is (100 x 2) that should be the recorded End Effector trajectory of the simulation. However printout of the results shows that all 100 rows have the same value.

Fitness function for evaluate therefor cannot be computed.

**Comment by xarthurx** [comment]
Try this:

![image](https://user-images.githubusercontent.com/1921878/54517552-4da82a80-4962-11e9-8352-1d2eb5825cf5.png)

Should fix the problem.

**Comment by yck011522** [comment]
Thanks, 
The line `sim.energy.fixedAngleEnabled = true;` fixed the problem.

**Comment by yck011522** [comment]
Perhaps this should be pulled into the code base.
