### ISSUE TITLE
Test Case for HingeJoint inconsistent with Readme.pdf

### ISSUE THREAD

**Issue by solraun** [computational-robotics-lab/comp-fab-a2#5]
In the readme you define the hinge joint constraint as follows:
![image](https://user-images.githubusercontent.com/6664280/54524603-aaabdc80-4972-11e9-9489-b091b29fb3bd.png)

The test passes only if we switch x_i and x_j (thus having the - in front of the x_i).
That might confuse some people.

**Comment by moritzge** [comment]
The jacobian should be computed according to how the constraint is implemented in the code:

https://github.com/computational-robotics-lab/comp-fab-a2/blob/c6507e02f1e9a184d08df1de58051021a04ce466/src/rbSimLib/Joint.h#L17
