### ISSUE TITLE
Jansen mechanism causing app to crash

### ISSUE THREAD

**Issue by kausalyamahadevan** [computational-robotics-lab/comp-fab-a2#6]
After passing the tests and running the app – when I switch to Jansen mechanism the app crashes and leaves the following error message. I am running this on a macbook and another student has the same issue (also macbook)
Assertion failed: (startRow >= 0 && BlockRows >= 0 && startRow + BlockRows <= xpr.rows() && startCol >= 0 && BlockCols >= 0 && startCol + BlockCols <= xpr.cols()), function Block, file /Users/amala/github/comp-fab-a2-kausalyamahadevan/ext/eigen/Eigen/src/Core/Block.h, line 133.
Abort trap: 6

**Comment by kausalyamahadevan** [comment]
It's because of an issue in my Jacobian (even though it passes the test)

**Comment by moritzge** [comment]
I pulled the latest commit, built and ran your code. I don't get any error. \
Are you still experiencing this error?

**Comment by GeneKao** [comment]
I just ran into the same error, my code also passed the test. 

```
Assertion failed: (startRow >= 0 && BlockRows >= 0 && startRow + BlockRows <= xpr.rows() && startCol >= 0 && BlockCols >= 0 && startCol + BlockCols <= xpr.cols()), function Block, file /usr/local/include/eigen3/Eigen/src/Core/Block.h, line 133.

Process finished with exit code 6
```

**Comment by kausalyamahadevan** [comment]
No, I rewrote the line so that it's fine! Somehow my code passed the test but I had not implemented the Jacobian correctly.
